version: '3.3'
services:
  k6:
    image: grafana/k6@sha256:d39047ea6c5981ac0abacec2ea32389f22a7aa68bc8902c08b356cc5dd74aac9
    container_name: k6
    volumes:
      - '${PWD}/src:/scripts'
    environment:
      - OCP_APIM_SUBSCRIPTION_KEY=${ocp_apim_subscription_key}
      - VARS=${env}.environment.json
      - TEST_TYPE=/scripts/test-types/${type}.json
      - K6_OUT=influxdb=http://nginx:8086/${db_name}
    command: run /scripts/${script}.js
    depends_on:
      - nginx

  nginx:
    image: nginx@sha256:d2eb56950b84efe34f966a2b92efb1a1a2ea53e7e93b94cdf45a27cf3cd47fc0
    container_name: nginx
    volumes:
      - '${PWD}/nginx/nginx.conf:/etc/nginx/nginx.conf'
    environment:
      - ENVIRONMENT=${env}
    ports:
      - "8086:8086"
      - "80:80"