apiVersion: v2
name: gpd-payments-pull
description: Microservice pagopa-gpd-payments-pull
type: application
version: 0.38.0
appVersion: 2.0.2-3-hikari
dependencies:
  - name: microservice-chart
    version: 2.8.0
    repository: "https://pagopa.github.io/aks-microservice-chart-blueprint"
